#!/usr/bin/env node

require("./settings");

const { withEmbyDisabled } = require("./lib/emby_controller");
const { listLibraryItems } = require("./lib/library_provider");
const { fixDirectoryTitles } = require("./lib/emby_updater");
const { createDB } = require("./lib/db");

async function main() {
  if (process.argv[2] === "-h" || process.argv[2] === "--help") {
    console.log(
      `emby-fixer: Make emby display music directories with their actual title.\nThere are no CLI args. Just configure it and run as root.`
    );
    return;
  }

  const db = createDB();
  try {
    const libraryItems = await listLibraryItems();

    await withEmbyDisabled(async () => {
      await fixDirectoryTitles(libraryItems, db);
    });
  } catch (err) {
    console.error(err);
  } finally {
    db.close().catch(err => {
      console.error(err.stack || err);
    });
  }
}

Promise.resolve()
  .then(() => main())
  .catch(err => {
    console.error(err.stack || err);
    process.exit(1);
  });
