#!/usr/bin/env node

require("./settings");

const { withEmbyDisabled } = require("./lib/emby_controller");
const { listLibraryItems } = require("./lib/library_provider");
const { fixDirectoryTitles, fixHugeAlbums } = require("./lib/emby_fixes");
const { createDB } = require("./lib/db");

async function main() {
  if (process.argv[2] === "-h" || process.argv[2] === "--help") {
    console.log(
      `emby-fixer: Execute a number of fixes on emby's library to make its Music collection functionality usable for folder view.

This should be run periodically (in a cron or a scheduler).
There are no CLI args. Just configure it and run as root.
`
    );
    return;
  }

  const db = createDB();
  try {
    const libraryItems = await listLibraryItems();

    await withEmbyDisabled(async () => {
      await fixHugeAlbums(libraryItems, db);
      await fixDirectoryTitles(libraryItems, db);
    });
  } catch (err) {
    console.error(err);
  } finally {
    db.close().catch(err => {
      console.error(err.stack || err);
    });
  }
}

Promise.resolve()
  .then(() => main())
  .catch(err => {
    console.error(err.stack || err);
    process.exit(1);
  });
